### PR TITLE
Garlicoin: add dnsseed.rshaw.space to DNS seed list

### PR DESCRIPTION
**Pull request by ryan-shaw**
I noticed the DNS seed node listed isn't working so I have created a DNS seed node located at https://github.com/ryan-shaw/garlicoin-seeder

There is a docker container that can be pulled from https://hub.docker.com/r/ryanshaw/garlicoin-seeder/tags/

This will be extremely useful to handle initial wallet syncs.

### CODE REVIEW

**Comment by ryan-shaw** [comment]
I have more commits coming to cleanup config too

**Comment by aaruel** [comment]
Both your PRs look good to merge. Before I do, do you have any more commits coming for either PR?

**Comment by ryan-shaw** [comment]
Nope, I'm currently trying to fix testnet, is anyone working on that?

**Comment by retosen** [comment]
I’m working on getting a new testnet up. It’ll not take long and I should’ve submitted a PR shortly.

**Pull request merged**
