### PR TITLE
Updated root peer list

### PR DESCRIPTION
**Pull request by BrennanMcDonald**
Removed the stale peers added at launch and replaced them with 4 new dedicated root nodes.

`85.10.198.242` -> notafoolsgarden
`91.205.172.38` -> freshgrlc.net
`67.207.87.24` -> garlicoin.org
`157.230.68.227` -> my dedicated node

### CODE REVIEW

**Review by pfych — APPROVED** [review]
Seems good however we really should look at expanding this list to contain more peers.

**Comment by pfych** [comment]
I'll merge once we've discussed updating the builds to contain these changes. Our Travis config seems to be broken.

**Comment by BrennanMcDonald** [comment]
> Seems good however we really should look at expanding this list to contain more peers.

I added an extra one that I'll maintain but right now there aren't a lot of reliable nodes.

> I'll merge once we've discussed updating the builds to contain these changes. Our Travis config seems to be broken.

Looks like litecoin and bitcoin updated their travis-ci build configurations so maybe we can check what they updated. Looks like it's an issue with `apt` failing to update.

**Comment by ryan-shaw** [comment]
Here's the output from my DNS seeder

```
# address                                        good  lastSuccess    %(2h)   %(8h)   %(1d)   %(7d)  %(30d)  blocks      svcs  version
66.151.242.154:42069                                1   1619011323  100.00% 100.00% 100.00%  99.99%  87.82%  2495386  0000040d  70017 "/GarlicoinCore:0.17.2/"
51.158.75.159:42069                                 1   1619011323  100.00% 100.00% 100.00%  99.99%  87.82%  2495386  0000040d  70017 "/GarlicoinCore:0.17.0/"
161.97.141.29:42069                                 1   1619011323  100.00% 100.00% 100.00%  99.99%  87.82%  2495386  0000040d  70017 "/GarlicoinCore:0.17.2/"
[2001:41d0:700:432::]:42069                         1   1619011323  100.00% 100.00% 100.00%  99.99%  87.81%  2495386  0000040d  70017 "/GarlicoinCore:0.17.2/"
145.239.0.50:42069                                  1   1619011323  100.00% 100.00% 100.00%  99.99%  87.81%  2495386  0000040d  70017 "/GarlicoinCore:0.17.2/"
31.25.241.224:42069                                 1   1619011323  100.00% 100.00% 100.00%  99.99%  87.80%  2495386  0000040d  70017 "/GarlicoinCore:0.17.2/"
[2a02:c205:0:5224::1]:42069                         1   1619011323  100.00% 100.00% 100.00%  99.99%  87.80%  2495386  0000000d  70016 "/GarlicoinCore:0.16.0.3/"
91.205.172.38:42069                                 1   1619011323  100.00% 100.00%  99.88%  99.86%  87.77%  2495386  0000000d  70016 "/GarlicoinCore:0.16.0.3/"
159.89.177.213:42069                                1   1619011323  100.00%  99.81%  99.27%  99.56%  87.60%  2495386  0000040d  70017 "/GarlicoinCore:0.17.2/"
134.209.205.182:42069                               1   1619011323  100.00% 100.00% 100.00%  99.85%  87.56%  2495386  0000000d  70016 "/GarlicoinCore:0.16.0.3/"
134.209.205.7:42069                                 1   1619011323  100.00%  99.99%  99.85%  99.72%  87.56%  2495386  0000000d  70016 "/GarlicoinCore:0.16.0.3/"
83.221.211.116:42069                                1   1619011323  100.00% 100.00% 100.00%  99.88%  87.31%  2495386  0000040d  70017 "/GarlicoinCore:0.17.2/"
73.225.203.103:42069                                1   1618326026    0.00%   0.00%   0.03%  29.04%  53.94%  2478683  0000040d  70017 "/GarlicoinCore:0.17.2/"
86.20.22.98:42069                                   0   1613989229   68.76%  25.54%  22.87%  28.05%   9.36%  2373272  0000040d  70017 "/GarlicoinCore:0.17.2/"
108.170.148.38:42069                                0   1613929137   71.51%  27.72%  25.92%  20.12%   6.19%  2371811  0000040d  70017 "/GarlicoinCore:0.17.2/"
98.144.147.221:42069                                0   1614989338   67.43%  25.34%  20.72%  19.44%   6.14%  2397591  0000040d  70017 "/GarlicoinCore:0.17.2/"
78.46.18.218:42069                                  0   1613866363   30.89%  15.87%  18.98%  10.53%   3.05%  2370285  0000040d  70017 "/GarlicoinCore:0.17.2/"
67.182.20.95:42069                                  0   1613816429   74.30%  60.41%  28.72%   4.84%   1.15%  2369069  0000040d  70017 "/GarlicoinCore:0.17.2/"
67.207.87.24:42069                                  0   1614904306   46.52%  50.32%  25.07%   4.30%   1.03%  2395521  0000040d  70017 "/GarlicoinCore:0.17.2/"
85.246.180.245:42069                                0   1613681516   58.59%  23.28%  14.97%   3.61%   0.91%  2365798  0000040d  70017 "/GarlicoinCore:0.17.2/"
174.22.112.26:42069                                 0   1613669095   57.97%  23.02%  13.57%   3.00%   0.75%  2365485  0000040d  70017 "/GarlicoinCore:0.17.2/"
176.149.34.180:42069                                0   1613824749    3.20%  14.61%   9.43%   1.79%   0.43%  2369275  0000040d  70017 "/GarlicoinCore:0.17.2/"
98.184.250.189:42069                                0   1614829723   69.29%  25.56%   9.37%   1.40%   0.33%  2393713  0000040d  70017 "/GarlicoinCore:0.17.2/"
69.138.119.192:42069                                0   1615055375   69.01%  25.39%   9.30%   1.38%   0.32%  2399197  0000040d  70017 "/GarlicoinCore:0.17.2/"
77.57.25.26:42069                                   0   1614942542   68.42%  25.03%   9.16%   1.36%   0.32%  2396454  0000040d  70017 "/GarlicoinCore:0.17.2/"
73.228.122.251:42069                                0   1613727316   55.61%  21.96%   8.16%   1.22%   0.29%  2366907  0000040d  70017 "/GarlicoinCore:0.17.2/"
64.201.114.211:42069                                0   1613939041   33.29%  14.70%   5.58%   0.84%   0.20%  2372052  0000040d  70017 "/GarlicoinCore:0.17.2/"
23.113.163.197:42069                                0   1614982120    7.02%   6.46%   4.04%   0.81%   0.20%  2397415  0000040d  70017 "/GarlicoinCore:0.17.2/"
```

if the node is not here it is likely not properly setup to be a root node, i.e. max connections, ports etc.

It can be parsed into a format used in https://github.com/GarlicoinOrg/Garlicoin/blob/master/src/chainparamsseeds.h using `contrib/seeds/generate-seeds.py`

**Comment by retosen** [comment]
I'm happy to merge this - obviously checks are failing but that's a separate issue and there's really no way these changes can break anything

**Comment by pfych** [comment]
Agree with @retosen, I’m happy for someone to merge this

**Pull request merged**
