### PR TITLE
Name Changing

### PR DESCRIPTION
**Pull request by honeycomb-project**
Preliminary work, renamed all permutations and instances of garlicoin to honeycomb
- garlicoin -> honeycomb
- garlicoind -> honeycombd (daemon)
- Garlicoin -> Honeycomb
- GarliCoin -> HoneyComb
- GRLC -> HNY

Also changed .TH GARLICOIN-QT -> .TH HONEYCOMB-QT on line 2 in garlicoin.qt.1 so the QT could compile.

### CODE REVIEW

**Comment by ryan-shaw** [comment]
@honeycomb-project yea... we aren't renaming to honeycomb

**Comment by retosen** [comment]
@ryan-shaw I think they're forking from us and accidentally submitted to the wrong repo - I did that to litecoin once lol

**Comment by honeycomb-project** [comment]
yeah i submitted to wrong repo sorry. anyway to remove this?

**Comment by ryan-shaw** [comment]
Nope

**Pull request closed without merging**
