### PR TITLE
[QT] Replace litecoin logos with garlicoin logos

### LINKED ISSUE #29: mac app icon still lightcoin logo
### Describe the issue
When running the Garlicoin-qt app the icon in the app bar is still light coin logo. 

screen shot 2018-01-25 at 10 52 59 am

### PR DESCRIPTION
**Pull request by nacgarg**
Fixes #29

### CODE REVIEW

**Comment by ryan-shaw** [comment]
replacing 1024x1024 with 227x227, could you replace it with the same resolution?

**Comment by nacgarg** [comment]
I'm not able to find a 1024x1024 version of the logo, should I just scale this image up?

**Comment by jacobbaratta** [comment]
You failed to fix the icns file. Please replace bitcoin.icns with this file and update your fork/PR (make sure to save it as bitcoin.icns): https://files.vkk.me/extra/234da4282176ebd74cd6182fcb19263dc203d644.icns

**Comment by nacgarg** [comment]
@jacobbaratta Thanks for the heads-up, fixed.

**Comment by retosen** [comment]
@nacgarg https://github.com/lmbda/grlc_logo this is the source for the garlicoin logos. If you could use them to update your PR that would be great.

**Comment by nacgarg** [comment]
@retosen fixed that as well.

**Review by ryan-shaw — APPROVED** [review]
LGTM

**Comment by jacobbaratta** [comment]
Here's an updated .icns file with the correct logo from the repo retosen linked: https://files.vkk.me/extra/b0615cfcd10ac340107a59605579c2fc88104c38.icns

Edit: It's worth noting that the logos from the repo retosen linked are slightly different from the main logo used by most garlicoin-related sites (like the subreddit/site/Discord). Why isn't there a full-rez version of the actual logo being used? **Is the actual logo wrong**?

See, this is what the logo everyone is using looks like:

bitcoin

And this is what the logo in the repo looks like:

bitcoin

**Comment by ryan-shaw** [comment]
Will merge for now

**Pull request merged**
