### PR TITLE
Officially detached and seperated from the Litecoin chain.

### PR DESCRIPTION
**Pull request by jdleo**
changes + explanations:  
  
**pszTimestamp** is the timestamp for the Genesis block. Right now the string is a placeholder. The naming convention for the genesis timestamp is usually the date and a message following it. Right now it's a placeholder string with a reminder to change this. The date will be the date of alpha release, I assume, or when we officially take the blockchain live.  
  
**Genesis output script** is the hardcoded scriptpubkey for the genesis block. It really doesn't matter what this is, but I deleted the first 4 values and made it 6969.  
  
**pchMessage** values can be literally any hex value, so I just changed them up. They really don't matter.  
  
Then, I deleted all references to the genesis block hashes, and the merkle root hashes. This is what officially detaches us from the Litecoin chain. You'll see they are 0x for now, this is a placeholder because we have to generate these values when we take the chain live.  
  
Lastly, in the CreateGenesisBlock method, the first argument is epoch time of the genesis block, and the second argument is the nNonce. I commented a reminder to change these two values. Epoch time has to be the current time of when we take the chain live, to promote transparency (so our users don't think we did anything sketchy), and the second argument is the nNonce which we will generate later.  
  
We are officially detached from the Litecoin chain.

### CODE REVIEW

**Comment by jdleo** [comment]
oh, and also, the reason for multiple instances of each is because the values needed to be modified for both testnet and mainnet

**Comment by jdleo** [comment]
Changed target spacing settings and circulation settings.  
  
Difficulty readjustment: ~1.4 days
Block spacing: ~60 seconds
Max coin supply: ~69,000,000

This is proportionate to Litecoin which allows us to leave miner confirmation windows and activation thresholds untouched. For activation threshold, it will take 8064 blocks which is 4 difficulty readjustments. This is also what Litecoin has.

**Comment by jdleo** [comment]
Oh also, I simply wrote a script to change instances of 84000000 to 69000000 so I noticed ironically there was a 69000000 instance in the hash checkpoints too. Those don't matter, since this is a new chain we'll have to delete those block checkpoints anyways (since those hashes won't even exist on our chain)

**Comment by aaruel** [comment]
Overridden by @retosen 's PR

**Pull request closed without merging**
